FrameFriend/FrameFriend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('accounts.urls')),
    path('',include('movies.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FrameFriend/home/urls.py
from django.urls import path
from . import views as v

app_name = 'home'
urlpatterns = [
    path('',v.homepage,name="index"),
    # path('search/', v.Search, name='search'),   
]

FrameFriend/movies/urls.py
from django.urls import path
from . import views as v

app_name = 'movie'
urlpatterns = [
    path('category/<uuid:id>/',v.ProductCategoryList,name='category'),
    path('products/',v.Product_List,name="product_list"),
    path('products/<uuid:id>/', v.Product_detail, name='product_detail'),
    path('products/add/', v.product_add, name='product_add'),
    path('products/<uuid:pk>/update/', v.product_update, name='product_update'),
    path('products/<uuid:pk>/delete/', v.product_delete, name='product_delete'),
    # path('search/', v.Search, name='search'),
]

FrameFriend/home/models.py
from django.db import models
# from autoslug import AutoSlugField

# Create your models here.
class Hero(models.Model):
    images          =   models.ImageField(upload_to='hero-image/', null=True, blank=True,)
    discription         =   models.TextField(blank=True,null=True)
    text                =   models.CharField(blank=True,null=True ,max_length=300)
    is_active           =   models.BooleanField(default=True)

class Slider(models.Model):
   image= models.ImageField(upload_to='slider-image/', null=True, blank=True,)
   subtitle=models.CharField(max_length=200)
   header1=models.CharField(max_length=300)
   header2=models.CharField(max_length=300)
   date  =  models.DateTimeField(auto_now_add=False , null=True, blank=True)
   is_active = models.BooleanField(default=True)

FrameFriend/home/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
# Create your views here.
from django.core.paginator import Paginator
from .models import *
from movies.models import *
from django.db.models import Q


# Create your views here.
def homepage(request):
    products = Movie.objects.all().order_by('-id')
    paginated = Paginator(products, 8)
    page_number = request.GET.get('page') #Get the requested page number from the URL
    product = paginated.get_page(page_number)
    context ={
        'product':product,
    }
    return render(request, 'User-Page/LandingPage/home.html',context)

def search(request):  # new
    if 'query' in request.GET:
        query = request.GET.get('query')
        if query:
            category = Category.objects.all()
            movie = Movie.objects.filter(product__title__icontains=query)
            movies = Movie.objects.filter(category=movie.category)
            # images = Images.objects.filter(movie_id=id)
            review = Review.objects.filter(movie=movie,status='True')
            context={
                'movie':movie,
                'movies':movies,
                'review': review,
            }
        
            return render(request, 'User-Page/Movies/product-list.html', context)
        return HttpResponseRedirect('/')

FrameFriend/templates/User-Page/LandingPage/category.html
{% extends 'User-Page/baseLayout.html' %}
{% load static %}
{% block title %}
Movie-Home
{% endblock title %}
{% block content  %}
<main class="main-content">
    <div class="container">
        <div class="page">
            <div class="breadcrumbs">
                <a href="/">Home</a>
                <span>Movie Review</span>
            </div>

            <div class="filters">
                
                {% comment %} <select name="#" id="#" placeholder="Choose Category">
                    {% for category in categories %}
                    <option value="#"><a href="/category/{{category.id}}">{{ category.name }}</a></option>
                    {% endfor %}
                </select> {% endcomment %}
                {% include "User-Page/Category/category.html" %}
            </div>
            
            <div class="movie-list">
                {% for m in product %}
                <div class="movie">
                   
                    <figure class="movie-poster"><a href="{% url 'movie:product_detail' m.id %}" className=""><img src="{{m.image.url}}" alt="{{m.website_url}}"></a></figure>
                    <div class="movie-title"><a href="{{m.website_url}}">{{m.title}}</a></div>
                    <p>{{m.description}}</p>
                    
                </div>
                {% endfor %}
                {% comment %} <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-4.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">The adventure of Tintin</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-5.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Hobbit</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-6.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Exists</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-1.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Drive hard</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-2.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Robocop</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-7.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Life of Pi</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-8.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">The Colony</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div> {% endcomment %}
            </div> <!-- .movie-list -->

            <div class="pagination">
                {% if product.has_previous %}
                <a href="?page={{product.previous_page_number}}" class="page-number prev"><i class="fa fa-angle-left"></i></a>
                {% endif %}
                {% for num in product.paginator.page_range %}
                {% if num == product.number %}
                <span class="page-number current">{{num}}</span>
                {% else %}
                <a href="?page={{num}}" class="page-number">{{num}}</a>
                {% endif %}
                {% endfor %}
                
                <a href="?page={{product.paginator.num_pages}}" class="page-number">Last</a>
                {% if page.has_next %}
                <a href="#" class="page-number">4</a>
                <a href="#" class="page-number">5</a>
                <a href="?page={{product.next_page_number}}" class="page-number next"><i class="fa fa-angle-right"></i></a>
                {% endif %}
            </div>
        </div>
    </div> <!-- .container -->
</main>
{% endblock %}

FrameFriend/templates/User-Page/LandingPage/home.html
{% extends 'User-Page/baseLayout.html' %}
{% load static %}
{% block title %}
Movie-Home
{% endblock title %}
{% block content  %}


<div id="site-content">
    <main class="main-content">
        <div class="container">
            <div class="page">
                <div class="row">
                    <div class="col-md-9">
                        <div class="slider">
                            <ul class="slides">
                                <li><a href="#"><img src="{% static 'dummy/11.jpg' %} " alt="11"></a></li>
<!--                                <li><a href="#"><img src="{% static ' dummy/11.jpg' %}" alt="11"></a></li>-->
                                <li><a href="#"><img src="{% static 'dummy/2.jpg' %} " alt="2"></a></li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="col-md-3">
                        <div class="row">
                            <div class="col-sm-6 col-md-12">
                                <div class="latest-movie">
                                    <a href="#"><img src=" {% static 'dummy/22.jpg' %}  " alt="Movie 1"></a>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-12">
                                <div class="latest-movie">
                                    <a href="#"><img src=" {% static 'dummy/33.jpg' %} " alt="Movie 2"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- .row -->
                
            <div class="filters">
                
                {% include "User-Page/Category/category.html" %}
            </div>
                <div class="row">
                    {% for m in product  %}
                    <div class="col-sm-6 col-md-3">
                        
                        <div class="latest-movie">
                           
                            <a href="{% url 'movie:product_detail' m.id %}"><img src="{{m.image.url}}" style="height: 400px;" alt="Movie 3"></a>
                            <h2 class="section-title " style="text-align: center;font-size: medium;padding-top: 9px;">{{m.title}}</h2>
                            <p style="text-align: center;font-size: medium;padding-top: 9px;">{{m.description}}</p>
                            
                        </div>
                        
                    </div>
                    {% endfor %}
                </div> <!-- .row -->
                
                <div class="row">
                    <div class="col-md-4">
                        <h2 class="section-title">December premiere</h2>
                        <p>Your Ultimate Destination for Movie Enthusiasts Dive into the world of cinema like never
before with FrameFriends, the premier online hub for movie lovers across the globe.</p>
                        <ul class="movie-schedule">
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                        </ul> <!-- .movie-schedule -->
                    </div>
                    <div class="col-md-4">
                        <h2 class="section-title">November premiere</h2>
                        <p>Your Ultimate Destination for Movie Enthusiasts Dive into the world of cinema like never
before with FrameFriends, the premier online hub for movie lovers across the globe.</p>
                        <ul class="movie-schedule">
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                        </ul> <!-- .movie-schedule -->
                    </div>
                    <div class="col-md-4">
                        <h2 class="section-title">October premiere</h2>
                        <p>Your Ultimate Destination for Movie Enthusiasts Dive into the world of cinema like never
before with FrameFriends, the premier online hub for movie lovers across the globe.</p>
                        <ul class="movie-schedule">
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                            <li>
                                <div class="date">16/12</div>
                                <h2 class="entry-title"><a href="#">Perspiciatis unde omnis</a></h2>
                            </li>
                        </ul> <!-- .movie-schedule -->
                    </div>
                </div>
            </div>
        </div> <!-- .container -->
    </main>
   
</div>
<!-- Default snippet for navigation -->
{% endblock  %}