FrameFriend/FrameFriend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('accounts.urls')),
    path('',include('movies.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FrameFriend/home/urls.py
from django.urls import path
from . import views as v

app_name = 'home'
urlpatterns = [
    path('',v.homepage,name="index"),
    # path('search/', v.Search, name='search'),   
]

FrameFriend/movies/urls.py
from django.urls import path
from . import views as v

app_name = 'movie'
urlpatterns = [
    path('category/<uuid:id>/',v.ProductCategoryList,name='category'),
    path('products/',v.Product_List,name="product_list"),
    path('products/<uuid:id>/', v.Product_detail, name='product_detail'),
    path('products/add/', v.product_add, name='product_add'),
    path('products/<uuid:pk>/update/', v.product_update, name='product_update'),
    path('products/<uuid:pk>/delete/', v.product_delete, name='product_delete'),
    # path('search/', v.Search, name='search'),
]

FrameFriend/templates/User-Page/Includes/footer.html
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="widget">
                    <h3 class="widget-title">About Us</h3>
                    <p>Your Ultimate Destination for Movie Enthusiasts Dive into the world of cinema like never
before with FrameFriends, the premier online hub for movie lovers across the globe.</p>
                </div>
            </div>
            <div class="col-md-2">
                <div class="widget">
                    <h3 class="widget-title">Recent Review</h3>
                    <ul class="no-bullet">
                        <li><a href="#">Spectacular</a></li>
                        <li><a href="#">Awesome</a></li>
                        <li><a href="#">Normal </a></li>
                        <li><a href="#">Good</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <div class="widget">
                    <h3 class="widget-title">Help Center</h3>
                    <ul class="no-bullet">
                        <li><a href="#">PP production</a></li>
                        <li><a href="#">SRR company</a></li>
                        <li><a href="#">Dolorem company</a></li>
                        <li><a href="#">Invenore veritae</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <div class="widget">
                    <h3 class="widget-title">Join Us</h3>
                    <ul class="no-bullet">
                        <li><a href="#">Framesfriends</a></li>
                        <li><a href="#">Movie world</a></li>
                        <li><a href="#">Dolorem respequem</a></li>
                        <li><a href="#">Film makes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <div class="widget">
                    <h3 class="widget-title">Social Media</h3>
                    <ul class="no-bullet">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Google+</a></li>
                        <li><a href="#">Pinterest</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <div class="widget">
                    <h3 class="widget-title">Newsletter</h3>
                    <form action="#" class="subscribe-form">
                        <input type="text" placeholder="Email Address">
                    </form>
                </div>
            </div>
        </div> <!-- .row -->

        <div class="colophon">Copyright 2014 Company name, Designed by Themezy. All rights reserved</div>
    </div> <!-- .container -->

</footer>

FrameFriend/templates/User-Page/Includes/navbar.html
{% load static %}
<header class="site-header">
    <div class="container">
        <a href="/" id="branding">
            <img src="{% static 'images/logo.png' %} " alt="" class="logo">
            <div class="logo-copy">
                <h1 class="site-title">Company Name</h1>
                <small class="site-description">Tagline goes here</small>
            </div>
        </a> <!-- #branding -->

        <div class="main-navigation">
            <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
            <ul class="menu">
                <li class="menu-item current-menu-item"><a href="/">Home</a></li>
                <li class="menu-item"><a href="{% url 'movie:product_list' %}">Movies</a></li>
                <li class="menu-item"><a href="">About</a></li>
                
                <li class="menu-item"><a href="joinus.html">Join us</a></li>
                {% if user.is_authenticated %}
                <li class="menu-item"><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="menu-item"><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul> <!-- .menu -->

            <form action="" class="search-form">
                <input type="search" id="query" name="query" placeholder="Enter Your choice">
                <button  type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div> <!-- .main-navigation -->

        <div class="mobile-navigation"></div>
    </div>
</header>