FrameFriend/FrameFriend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('accounts.urls')),
    path('',include('movies.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FrameFriend/home/urls.py
from django.urls import path
from . import views as v

app_name = 'home'
urlpatterns = [
    path('',v.homepage,name="index"),
    # path('search/', v.Search, name='search'),   
]

FrameFriend/movies/urls.py
from django.urls import path
from . import views as v

app_name = 'movie'
urlpatterns = [
    path('category/<uuid:id>/',v.ProductCategoryList,name='category'),
    path('products/',v.Product_List,name="product_list"),
    path('products/<uuid:id>/', v.Product_detail, name='product_detail'),
    path('products/add/', v.product_add, name='product_add'),
    path('products/<uuid:pk>/update/', v.product_update, name='product_update'),
    path('products/<uuid:pk>/delete/', v.product_delete, name='product_delete'),
    # path('search/', v.Search, name='search'),
]

FrameFriend/movies/models.py
# Create your models here.
from django.db import models
# from autoslug import AutoSlugField
import uuid
import os
import random
from django.template.defaultfilters import slugify
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Avg, Count

# Create your models here.
class Category(models.Model):
    id    = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name            =   models.CharField(max_length=255,db_index=True)
    image          =   models.ImageField(upload_to='category-image', null=True, blank=True,)
    # slug             =   AutoSlugField(populate_from='name',max_length=255,unique=True,null=True)
    description      =   models.TextField(blank=True,null=True)
    parent_id        =   models.ForeignKey('self', on_delete=models.SET_NULL, null=True,blank=True, related_name='category_parent')
    is_active        =   models.BooleanField(default=True)   
    created_date     =   models.DateTimeField(auto_now_add=True)
    modified_date    =   models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})



class Movie(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    id    = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name= 'product_categotry',null=True,blank=True) #many to one relation with Category
    title = models.CharField(max_length=150)
    minutes = models.PositiveIntegerField(default=0)
    seconds = models.PositiveIntegerField(default=0)
    director = models.CharField(max_length=150)
    stars = models.CharField(max_length=150)
    writers = models.CharField(max_length=150)
    description = models.CharField(max_length=450)
    detailed_description = models.TextField(blank=True)
    image=models.ImageField(upload_to='images/',null=False)
    website_url = models.URLField()
    releas_date = models.DateTimeField(auto_created=True)
    status=models.CharField(max_length=10,choices=STATUS)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title


    ## method to create a fake table field in read only mode
    def image_tag(self):
        if self.image.url is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
        else:
            return ""

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    def avaregereview(self):
        reviews = Review.objects.filter(product=self, status='True').aggregate(avarage=Avg('rate'))
        avg=0
        if reviews["avarage"] is not None:
            avg=float(reviews["avarage"])
        return avg

    def countreview(self):
        reviews = Review.objects.filter(product=self, status='True').aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt


class Images(models.Model):
    product=models.ForeignKey(Movie,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )
class Reviews(models.Model):
    
    id    = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    comment = models.TextField()
    rate = models.PositiveIntegerField()
    status=models.CharField(max_length=10,choices=STATUS, default=STATUS[0][0])
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
   

FrameFriend/movies/forms.py
from django import forms
from .models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = [
            'category', 'title', 'minutes', 'seconds', 'director', 'stars', 
            'writers', 'description', 'detailed_description', 'image', 
            'website_url', 'status', 'releas_date'
        ]
        widgets = {
            'releas_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['subject', 'comment', 'rate']

FrameFriend/movies/views.py
from django.shortcuts import get_object_or_404, render, redirect
# Create your views here.   
from django.core.paginator import Paginator
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *



def ProductCategoryList(request, id,):
    category = Category.objects.get(id=id)
    movie =    Movie.objects.filter(category=category)
    paginated = Paginator(movie, 8)
    page_number = request.GET.get('page') #Get the requested page number from the URL
    
    product = paginated.get_page(page_number)
    context ={
        'category': category,
        'product': product
            }
    print(category)
    return render(request, 'User-Page/LandingPage/category.html', context)


def Product_List(request):
    products = Movie.objects.all().order_by('-id')
    paginated = Paginator(products, 8)
    page_number = request.GET.get('page') #Get the requested page number from the URL
    product = paginated.get_page(page_number)
    context ={
        'product':product,
    }
    return render(request,'User-Page/Movies/product-list.html',context)

@login_required(login_url='login')
def Product_detail(request,id):
    query = request.GET.get('q')
    category = Category.objects.all()
    movie = Movie.objects.get(pk=id)
    movies = Movie.objects.filter(category=movie.category)
    # images = Images.objects.filter(movie_id=id)
    reviews = Reviews.objects.filter(movie=movie,status ='New')
    
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie = movie
            review.user = request.user  # Set the user
            review.save()
            return redirect('movie:product_detail', id=movie.id)
    else:
        form = ReviewForm()
    context = {
                'movie': movie,
                'movies':movies,
                'reviews': reviews,
                'form': form
               }
               
    return render(request,'User-Page/Movies/Movie_detail.html',context)


@login_required(login_url='login')
def product_add(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)  # Include request.FILES to handle file uploads
        if form.is_valid():
            new_movie = form.save()
            return redirect('movie:product_detail', id=new_movie.id)
        else:
            print(form.errors)  # Print form errors to the console for debugging
    else:
        form = ProductForm()
    return render(request, 'User-Page/Movies/movie_add.html', {'form': form})

@login_required(login_url='login')
def product_update(request, pk):
    movie = get_object_or_404(Movie, id=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=movie)  # Include request.FILES
        if form.is_valid():
            form.save()
            return redirect('movie:product_detail', id=movie.id)
        else:
            print(form.errors)  # Print form errors to the console for debugging
    else:
        form = ProductForm(instance=movie)
    return render(request, 'User-Page/Movies/movie_update.html', {'form': form})


@login_required(login_url='login')
def product_delete(request, pk):
    movie = get_object_or_404(Movie, id=pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movie:product_list')  # Redirect to a list or another appropriate view
    return render(request, 'User-Page/Movies/movie_confirm_delete.html', {'movie': movie})

FrameFriend/templates/User-Page/Movies/Movie_detail.html
{% extends 'User-Page/baseLayout.html' %}
{% load static %}
{% block title %}
Movie-Home
{% endblock title %}
{% block content  %}
<main class="main-content">
    <div class="container">
        <div class="page">
            <div class="breadcrumbs">
                <a href="/">Home</a>
                <a href="review.html">Movie Review</a>
                <span>The Croods</span>
            </div>

            <div class="content">
                <div class="row">
                    <div class="col-md-6">
                        <figure class="movie-poster"><img src="{{movie.image.url}}" style="width: 100%; height: 500px;" alt="#"></figure>
                    </div>
                    <div class="col-md-6">
                        <h2 class="movie-title">{{movie.title}}</h2>
                        <div class="movie-summary">
                            <p>{{movie.description}}</p>

<!--                            <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit sed.</p>-->
                        </div>
                        <ul class="movie-meta">
                            <li><strong>Rating:</strong> 
                                <div class="star-rating" title="Rated 4.00 out of 5"><span style="width:80%"><strong class="rating">4.00</strong> out of 5</span></div>
                            </li>
                            <li><strong>Length:</strong> {{movie.minutes}} h : {{movie.seconds}} m</li>
                            <li><strong>Premiere:</strong> {{movie.releas_date}}</li>
                            <li><strong>Category:</strong>{{movie.category}}</li>
                        </ul>

                        <ul class="starring">
                            <li><strong>Directors:</strong> {{movie.director}}</li>
                            <li><strong>Writers:</strong>{{movie.writers}} </li>
                            <li><strong>Stars:</strong> {{movie.stars}}</li>
                            <li><strong style=""> You Tube : <a href="{{movie.website_url}}"><img src="{% static 'images\icons.png' %}" alt="" srcset=""></a></strong></li>
                        </ul>
                    </div>
                </div> <!-- .row -->
                <div class="entry-content">
                    <p>{{movie.detailed_description}}</p>
                </div>
            </div>
        </div>
    </div> <!-- .container -->
</main>
<main class="main-content">
    <div class="container">
        <div class="page">
            <div class="breadcrumbs">
                <a href="index.html">Home</a>
                <span>Contact</span>
            </div>

            <div class="content">
                <div class="row">
                    <div class="col-md-4">
                        <h2>Contact</h2>
                        <ul class="contact-detail">
                            <li>
                                <img src="images/icon-contact-map.png" alt="#">
                                <address><span>Company name. INC</span> <br>550 Avenue Street, New york</address>
                            </li>
                            <li>
                                <img src="images/icon-contact-phone.png" alt="">
                                <a href="tel:1590912831">+1 590 912 831</a>
                            </li>
                            <li>
                                <img src="images/icon-contact-message.png" alt="">
                                <a href="mailto:contact@companyname.com">contact@companyname.com</a>
                            </li>
                        </ul>
                        <div class="contact-form">
                            <input type="text" class="name" placeholder="name...">
                            <input type="text" class="email" placeholder="email...">
                            <input type="text" class="website" placeholder="website...">
                            <textarea class="message" placeholder="message..."></textarea>
                            <input type="submit" value="Send Message ">

                        </div>
                    </div>
                    <div class="reviews">
                        <h2>Reviews</h2>
                        {% comment %} {% if review %} {% endcomment %}
                            <ul>
                                {% for r in reviews %}
                                    <li>
                                        <strong>{{ r.subject }}</strong> (Rating: {{ r.rate }}/5)
                                        <p>{{ r.comment }}</p>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% comment %} {% else %}
                            <p>No reviews yet.</p>
                        {% endif %} {% endcomment %}
                    </div>
                
                    <div class="review-form">
                        <h2>Submit a Review</h2>
                        <form method="post" action="">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">Submit Review</button>
                        </form>
                    </div>
                
                </div>
            </div>
        </div>
    </div> <!-- .container -->
</main>
{% endblock %}

FrameFriend/templates/User-Page/Movies/movie_add.html
<body>
    <h1>Add Product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Product</button>
    </form>
    <a href="{% url 'movie:product_list' %}">Back to Product List</a>
    <ul>
<!--        {% for m in movie %}-->
            <li>
                <a href="{% url 'movie:product_detail' pk=m.pk %}">{{ m.title }}</a>
                <a href="{% url 'movie:product_update' pk=m.pk %}">(Edit)</a>
                <a href="{% url 'movie:product_delete' pk=m.pk %}">(Delete)</a>
            </li>
<!--        {% endfor %}-->
    </ul>
</body>
</html>

FrameFriend/templates/User-Page/Movies/movie_confirm_delete.html
<!-- In your template directory: User-Page/Movies/movie_confirm_delete.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Movie</title>
</head>
<body>
    <h1>Are you sure you want to delete this movie?</h1>
    <p>{{ movie.title }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
        {% comment %} <a href="{% url 'movie:product_detail' pk=m.id %}">Cancel</a> {% endcomment %}
    </form>
</body>
</html>

FrameFriend/templates/User-Page/Movies/movie_update.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Update Product</title>
    <link rel="stylesheet" type="text/css" href="{% static 'products/styles.css' %}">
</head>
<body>
    <h1>Update Product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Product</button>
    </form>
    {% comment %} <a href="{% url 'movie:product_detail' pk=movie.pk %}">Back to Product</a> {% endcomment %}
</body>
</html>

FrameFriend/templates/User-Page/Movies/product-list.html
{% extends 'User-Page/baseLayout.html' %}
{% load static %}
{% block title %}
Movie-Home
{% endblock title %}
{% block content  %}
<main class="main-content">
    <div class="container">
        <div class="page">
            <div class="breadcrumbs">
                <a href="/">Home</a>
                <span>Movie Review</span>
                <li class="menu-item"><a href="{% url 'movie:product_add' %}">Add</a></li>
            </div>

            <div class="filters">
                
                <select name="#" id="#" placeholder="Choose Category">
                    {% for category in categories %}
                    <option value=""><a href="/category/{{category.id}}">{{ category.name }}</a></option>
                    {% endfor %}
                </select>
                {% comment %} <select name="#" id="#">
                    <option value="#">2012</option>
                    <option value="#">2013</option>
                    <option value="#">2014</option>
                </select> {% endcomment %}
            </div>
            
            <div class="movie-list">
                {% for m in product %}
                <div class="movie">
                   
                    <figure class="movie-poster"><a href="{% url 'movie:product_detail' m.id %}" className=""><img src="{{m.image.url}}" alt="{{m.website_url}}"></a></figure>
                    <div class="movie-title"><a href="{{m.website_url}}">{{m.title}}</a></div>
                    <p>{{m.description}}</p>
                    <a href="{% url 'movie:product_update' pk=m.pk %}">(Edit)</a>
                    <a href="{% url 'movie:product_delete' pk=m.pk %}">(delete)</a>

                </div>
                {% endfor %}
                {% comment %} <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-4.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">The adventure of Tintin</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-5.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Hobbit</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-6.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Exists</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-1.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Drive hard</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-2.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Robocop</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-7.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">Life of Pi</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div>
                <div class="movie">
                    <figure class="movie-poster"><img src="dummy/thumb-8.jpg" alt="#"></figure>
                    <div class="movie-title"><a href="single.html">The Colony</a></div>
                    <p>Sed ut perspiciatis unde omnis iste natus error voluptatem doloremque.</p>
                </div> {% endcomment %}
            </div> <!-- .movie-list -->

            <div class="pagination">
                {% if product.has_previous %}
                <a href="?page={{product.previous_page_number}}" class="page-number prev"><i class="fa fa-angle-left"></i></a>
                {% endif %}
                {% for num in product.paginator.page_range %}
                {% if num == product.number %}
                <span class="page-number current">{{num}}</span>
                {% else %}
                <a href="?page={{num}}" class="page-number">{{num}}</a>
                {% endif %}
                {% endfor %}
                
                <a href="?page={{product.paginator.num_pages}}" class="page-number">Last</a>
                {% if page.has_next %}
                <a href="#" class="page-number">4</a>
                <a href="#" class="page-number">5</a>
                <a href="?page={{product.next_page_number}}" class="page-number next"><i class="fa fa-angle-right"></i></a>
                {% endif %}
            </div>
        </div>
    </div> <!-- .container -->
</main>
{% endblock %}